
GET http://localhost:3000/api/items/getitems


### 
POST http://localhost:3000/api/items/postitems
Content-Type: application/json

{
    "name" : "Voltas 1.4 Ton 3 Star Inverter Split AC(Copper, Adjustable Cooling, Anti-dust Filter, 2023 Model, 173V Vectra Platina, White)",
    "price" : 30900,
    "category" : "electronics",
    "description" : "Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load. Convertible / adjustable with 4 cooling modes through remote control to operate in different tonnages for different cooling needs (20% to 120% capacity)",
    "image" : "https://m.media-amazon.com/images/I/51wIJED3K-L._SL1500_.jpg"
}

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name":"test",
    "password":"test"
}


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "name":"test",
    "password":"test"
}